version: '3'

services:
  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php8.2-fpm:latest
    container_name: app
    restart: unless-stopped
    tty: true
    depends_on:
        - db
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    command: >
        bash -c "
          while !</dev/tcp/db/3306; do sleep 1; done
          php database/migration.php
          php-fpm"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.33
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: simple-blog
      MYSQL_PASSWORD: simple-blog
      MYSQL_USER: simple-blog
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local